"""Recompute the recorded Phase 2 runs over retrieval-eligible items (approved follow-up).

Read-only over eval/baselines/phase2/*/results.json: nothing is re-run and the original raw
metrics (SUMMARY.md) stay as recorded. Uses eval/datasets/retrieval-v0/task-types.json
(structural rule: an item is 'retrieval' when every required fact has a satisfying parent with
retrieval children). Writes SUMMARY-eligible.md and summary-eligible.json.

    uv --directory backend run python ../scripts/phase2_eligible.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from marketsignal.evaluation.metrics import ItemScore, aggregate
from marketsignal.evaluation.stats import (
    bootstrap_mean,
    mcnemar_exact,
    paired_bootstrap_diff,
    wilson,
)

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "eval" / "baselines" / "phase2"
TASKS = ROOT / "eval" / "datasets" / "retrieval-v0" / "task-types.json"
PAIRS = {
    "06-final-dev": [("dense", "hybrid"), ("dense", "hybrid-rerank"), ("hybrid", "hybrid-rerank")],
    "07-test-milestone-c3": [
        ("dense", "hybrid"),
        ("dense", "hybrid-rerank"),
        ("hybrid", "hybrid-rerank"),
    ],
    "07-test-milestone-c2": [("baseline-dense", "hybrid@c2")],
}
TARGET_RECALL10 = 0.85


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


def _ci(d: dict[str, float]) -> str:
    return f"{_pct(d['estimate'])} [{_pct(d['low'])}-{_pct(d['high'])}]"


def scores(arm: dict[str, Any], keep: set[str]) -> dict[str, ItemScore]:
    return {
        i["item_id"]: ItemScore(i["item_id"], i["fact_ranks"])
        for i in arm["items"]
        if i["item_id"] in keep
    }


def main() -> int:
    tasks = json.loads(TASKS.read_text())
    eligible = {k for k, v in tasks["items"].items() if v["task_type"] == "retrieval"}
    rows: list[dict[str, Any]] = []
    comparisons: list[dict[str, Any]] = []
    for results in sorted(RUNS.glob("*/results.json")):
        report = json.loads(results.read_text())
        run = results.parent.name
        for arm_name, arm in report["arms"].items():
            s = list(scores(arm, eligible).values())
            agg = aggregate(s)
            n = len(s)
            rows.append(
                {
                    "run": run,
                    "split": report["split"],
                    "arm": arm_name,
                    "n_eligible": n,
                    "n_all": len(arm["items"]),
                    "hit@1": wilson(sum(x.hit_at(1) for x in s), n).as_dict(),
                    "hit@10": wilson(sum(x.hit_at(10) for x in s), n).as_dict(),
                    "recall@10": bootstrap_mean([x.recall_at(10) for x in s]).as_dict(),
                    "recall@20": bootstrap_mean([x.recall_at(20) for x in s]).as_dict(),
                    "mrr": bootstrap_mean([x.reciprocal_rank() for x in s]).as_dict(),
                    "raw_recall@10_all_items": arm["metrics"]["recall@10"],
                    "meets_recall@10_0.85": agg["recall@10"] >= TARGET_RECALL10,
                }
            )
        for a, b in PAIRS.get(run, []):
            sa, sb = scores(report["arms"][a], eligible), scores(report["arms"][b], eligible)
            ids = sorted(sa)
            entry: dict[str, Any] = {"run": run, "a": a, "b": b, "n": len(ids)}
            for k in (1, 10):
                t = mcnemar_exact([sa[i].hit_at(k) for i in ids], [sb[i].hit_at(k) for i in ids])
                entry[f"hit@{k}"] = {"b_gains": t.only_b, "b_losses": t.only_a, "p": t.p_value}
            entry["d_mrr"] = paired_bootstrap_diff(
                [sa[i].reciprocal_rank() for i in ids], [sb[i].reciprocal_rank() for i in ids]
            ).as_dict()
            entry["d_recall@10"] = paired_bootstrap_diff(
                [sa[i].recall_at(10) for i in ids], [sb[i].recall_at(10) for i in ids]
            ).as_dict()
            comparisons.append(entry)
    out = {"composition": tasks["composition"], "rows": rows, "comparisons": comparisons}
    (RUNS / "summary-eligible.json").write_text(json.dumps(out, indent=1) + "\n")

    lines = [
        "# Phase 2 runs over retrieval-eligible items (generated by scripts/phase2_eligible.py)",
        "",
        "Recomputed from the recorded results; the raw all-item metrics stay in SUMMARY.md.",
        f"Task composition: dev {tasks['composition']['dev']},"
        f" test {tasks['composition']['test']}.",
        "Analytics-only items (facts only in child-less numeric rows, ADR-0003) and multi-tool",
        "items stay in the dataset and are excluded from retrieval-quality denominators.",
        "",
        "| run | split | arm | n | hit@1 | hit@10 | recall@10 | recall@20 | MRR "
        "| raw recall@10 (all items) | recall@10 ≥ 0.85 |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['run']} | {r['split']} | {r['arm']} | {r['n_eligible']}/{r['n_all']} | "
            f"{_ci(r['hit@1'])} | {_ci(r['hit@10'])} | {_ci(r['recall@10'])} | "
            f"{_ci(r['recall@20'])} | {_ci(r['mrr'])} | {_pct(r['raw_recall@10_all_items'])} | "
            f"{'yes' if r['meets_recall@10_0.85'] else 'no'} |"
        )
    lines += [
        "",
        "## Paired comparisons (retrieval-eligible items)",
        "",
        "| run | A → B | n | hit@1 B gains/losses (p) | hit@10 B gains/losses (p) "
        "| ΔMRR | Δrecall@10 |",
        "|---|---|---|---|---|---|---|",
    ]

    def diff(d: dict[str, float]) -> str:
        return f"{d['estimate']:+.3f} [{d['low']:+.3f}, {d['high']:+.3f}]"

    for c in comparisons:
        h1, h10 = c["hit@1"], c["hit@10"]
        lines.append(
            f"| {c['run']} | {c['a']} → {c['b']} | {c['n']} | "
            f"{h1['b_gains']}/{h1['b_losses']} ({h1['p']:.3f}) | "
            f"{h10['b_gains']}/{h10['b_losses']} ({h10['p']:.3f}) | "
            f"{diff(c['d_mrr'])} | {diff(c['d_recall@10'])} |"
        )
    (RUNS / "SUMMARY-eligible.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
