"""Summarise every recorded Phase 2 run (eval/baselines/phase2/*/results.json).

For each run and arm: full-set metrics with their 95% intervals, the same metrics on the
lane-reachable subset (items whose facts are not only in child-less numeric rows, see
reachability.json), and end-to-end latency. Writes SUMMARY.md and summary.json next to the runs.
Read-only over recorded results; it never re-runs retrieval.

    uv --directory backend run python ../scripts/phase2_summary.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from marketsignal.evaluation.metrics import ItemScore, aggregate
from marketsignal.evaluation.stats import bootstrap_mean, wilson

ROOT = Path(__file__).resolve().parents[1] / "eval" / "baselines" / "phase2"


def _pct(x: float) -> str:
    return f"{100 * x:.1f}"


def main() -> int:
    reach = json.loads((ROOT / "reachability.json").read_text())["items"]
    rows: list[dict[str, Any]] = []
    for results in sorted(ROOT.glob("*/results.json")):
        report = json.loads(results.read_text())
        for arm, data in report["arms"].items():
            scores = [ItemScore(i["item_id"], i["fact_ranks"]) for i in data["items"]]
            reachable = [s for s in scores if reach[s.item_id]["any_reachable"]]
            sub = aggregate(reachable)
            n = len(scores)
            iv = data["intervals"]
            lat = data["latency_ms"]
            rows.append(
                {
                    "run": results.parent.name,
                    "split": report["split"],
                    "git": report["run"].get("git"),
                    "arm": arm,
                    "n": n,
                    "hit@1": iv["hit@1"],
                    "hit@10": iv["hit@10"],
                    "recall@10": iv["recall@10"],
                    "recall@20": iv["recall@20"],
                    "mrr": iv["mrr"],
                    "reachable_n": len(reachable),
                    "reachable_hit@10": wilson(
                        sum(1 for s in reachable if s.hit_at(10)), len(reachable)
                    ).as_dict(),
                    "reachable_recall@10": sub.get("recall@10"),
                    "reachable_mrr": bootstrap_mean(
                        [s.reciprocal_rank() for s in reachable]
                    ).as_dict(),
                    "latency_total_ms": lat.get("total_ms"),
                    "latency_rerank_ms": lat.get("rerank_ms"),
                }
            )
    (ROOT / "summary.json").write_text(json.dumps(rows, indent=1) + "\n")

    def ci(d: dict[str, float]) -> str:
        return f"{_pct(d['estimate'])} [{_pct(d['low'])}-{_pct(d['high'])}]"

    lines = [
        "# Phase 2 recorded runs (generated by scripts/phase2_summary.py)",
        "",
        "Full set, then the lane-reachable subset (items not answerable only from child-less",
        "numeric rows). 95% CIs: Wilson for hit rates, bootstrap for recall/MRR. Latency is",
        "end-to-end in-process p50/p95 (ms).",
        "",
        "| run | split | arm | n | hit@1 | hit@10 | recall@10 | recall@20 (pool) | MRR "
        "| reachable n | reachable hit@10 | reachable MRR | p50 / p95 ms |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lat = r["latency_total_ms"] or {"p50": "-", "p95": "-"}
        lines.append(
            f"| {r['run']} | {r['split']} | {r['arm']} | {r['n']} | {ci(r['hit@1'])} | "
            f"{ci(r['hit@10'])} | {ci(r['recall@10'])} | {ci(r['recall@20'])} | {ci(r['mrr'])} | "
            f"{r['reachable_n']} | {ci(r['reachable_hit@10'])} | {ci(r['reachable_mrr'])} | "
            f"{lat['p50']} / {lat['p95']} |"
        )
    (ROOT / "SUMMARY.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
